/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninCallbackRouteImport } from './routes/signin-callback'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LocalRouteImport } from './routes/local'
import { Route as ITwinsRouteImport } from './routes/iTwins'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as LocalFileNameRouteImport } from './routes/local_.$fileName'
import { Route as ITwinITwinIdRouteImport } from './routes/iTwin_.$iTwinId'
import { Route as BriefcaseFileNameRouteImport } from './routes/briefcase.$fileName'
import { Route as ITwinITwinIdIModelIModelIdRouteImport } from './routes/iTwin.$iTwinId.iModel.$iModelId'

const IndexLazyRouteImport = createFileRoute('/')()

const SigninCallbackRoute = SigninCallbackRouteImport.update({
  id: '/signin-callback',
  path: '/signin-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/local.lazy').then((d) => d.Route))
const ITwinsRoute = ITwinsRouteImport.update({
  id: '/iTwins',
  path: '/iTwins',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blank.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LocalFileNameRoute = LocalFileNameRouteImport.update({
  id: '/local_/$fileName',
  path: '/local/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const ITwinITwinIdRoute = ITwinITwinIdRouteImport.update({
  id: '/iTwin_/$iTwinId',
  path: '/iTwin/$iTwinId',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefcaseFileNameRoute = BriefcaseFileNameRouteImport.update({
  id: '/briefcase/$fileName',
  path: '/briefcase/$fileName',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/briefcase.$fileName.lazy').then((d) => d.Route),
)
const ITwinITwinIdIModelIModelIdRoute =
  ITwinITwinIdIModelIModelIdRouteImport.update({
    id: '/iTwin/$iTwinId/iModel/$iModelId',
    path: '/iTwin/$iTwinId/iModel/$iModelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/blank': typeof BlankRoute
  '/iTwins': typeof ITwinsRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/signin-callback': typeof SigninCallbackRoute
  '/briefcase/$fileName': typeof BriefcaseFileNameRoute
  '/iTwin/$iTwinId': typeof ITwinITwinIdRoute
  '/local/$fileName': typeof LocalFileNameRoute
  '/iTwin/$iTwinId/iModel/$iModelId': typeof ITwinITwinIdIModelIModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/blank': typeof BlankRoute
  '/iTwins': typeof ITwinsRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/signin-callback': typeof SigninCallbackRoute
  '/briefcase/$fileName': typeof BriefcaseFileNameRoute
  '/iTwin/$iTwinId': typeof ITwinITwinIdRoute
  '/local/$fileName': typeof LocalFileNameRoute
  '/iTwin/$iTwinId/iModel/$iModelId': typeof ITwinITwinIdIModelIModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/blank': typeof BlankRoute
  '/iTwins': typeof ITwinsRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/signin-callback': typeof SigninCallbackRoute
  '/briefcase/$fileName': typeof BriefcaseFileNameRoute
  '/iTwin_/$iTwinId': typeof ITwinITwinIdRoute
  '/local_/$fileName': typeof LocalFileNameRoute
  '/iTwin/$iTwinId/iModel/$iModelId': typeof ITwinITwinIdIModelIModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blank'
    | '/iTwins'
    | '/local'
    | '/settings'
    | '/signin-callback'
    | '/briefcase/$fileName'
    | '/iTwin/$iTwinId'
    | '/local/$fileName'
    | '/iTwin/$iTwinId/iModel/$iModelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blank'
    | '/iTwins'
    | '/local'
    | '/settings'
    | '/signin-callback'
    | '/briefcase/$fileName'
    | '/iTwin/$iTwinId'
    | '/local/$fileName'
    | '/iTwin/$iTwinId/iModel/$iModelId'
  id:
    | '__root__'
    | '/'
    | '/blank'
    | '/iTwins'
    | '/local'
    | '/settings'
    | '/signin-callback'
    | '/briefcase/$fileName'
    | '/iTwin_/$iTwinId'
    | '/local_/$fileName'
    | '/iTwin/$iTwinId/iModel/$iModelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BlankRoute: typeof BlankRoute
  ITwinsRoute: typeof ITwinsRoute
  LocalRoute: typeof LocalRoute
  SettingsRoute: typeof SettingsRoute
  SigninCallbackRoute: typeof SigninCallbackRoute
  BriefcaseFileNameRoute: typeof BriefcaseFileNameRoute
  ITwinITwinIdRoute: typeof ITwinITwinIdRoute
  LocalFileNameRoute: typeof LocalFileNameRoute
  ITwinITwinIdIModelIModelIdRoute: typeof ITwinITwinIdIModelIModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin-callback': {
      id: '/signin-callback'
      path: '/signin-callback'
      fullPath: '/signin-callback'
      preLoaderRoute: typeof SigninCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iTwins': {
      id: '/iTwins'
      path: '/iTwins'
      fullPath: '/iTwins'
      preLoaderRoute: typeof ITwinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local_/$fileName': {
      id: '/local_/$fileName'
      path: '/local/$fileName'
      fullPath: '/local/$fileName'
      preLoaderRoute: typeof LocalFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iTwin_/$iTwinId': {
      id: '/iTwin_/$iTwinId'
      path: '/iTwin/$iTwinId'
      fullPath: '/iTwin/$iTwinId'
      preLoaderRoute: typeof ITwinITwinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefcase/$fileName': {
      id: '/briefcase/$fileName'
      path: '/briefcase/$fileName'
      fullPath: '/briefcase/$fileName'
      preLoaderRoute: typeof BriefcaseFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iTwin/$iTwinId/iModel/$iModelId': {
      id: '/iTwin/$iTwinId/iModel/$iModelId'
      path: '/iTwin/$iTwinId/iModel/$iModelId'
      fullPath: '/iTwin/$iTwinId/iModel/$iModelId'
      preLoaderRoute: typeof ITwinITwinIdIModelIModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BlankRoute: BlankRoute,
  ITwinsRoute: ITwinsRoute,
  LocalRoute: LocalRoute,
  SettingsRoute: SettingsRoute,
  SigninCallbackRoute: SigninCallbackRoute,
  BriefcaseFileNameRoute: BriefcaseFileNameRoute,
  ITwinITwinIdRoute: ITwinITwinIdRoute,
  LocalFileNameRoute: LocalFileNameRoute,
  ITwinITwinIdIModelIModelIdRoute: ITwinITwinIdIModelIModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
