packages:
  - ui/*
  - apps/*
  - e2e-tests
  - tools/codemod
  - docs/storybook

catalog:
  # iTwin.js core packages
  "@itwin/appui-abstract": rc
  "@itwin/core-backend": rc
  "@itwin/core-bentley": rc
  "@itwin/core-common": rc
  "@itwin/core-electron": rc
  "@itwin/core-frontend": rc
  "@itwin/core-geometry": rc
  "@itwin/core-i18n": rc
  "@itwin/core-orbitgt": rc
  "@itwin/core-quantity": rc
  "@itwin/ecschema-metadata": rc
  "@itwin/ecschema-rpcinterface-common": rc
  "@itwin/ecschema-rpcinterface-impl": rc
  "@itwin/editor-backend": rc
  "@itwin/editor-common": rc
  "@itwin/editor-frontend": rc
  "@itwin/express-server": rc
  "@itwin/frontend-devtools": rc
  "@itwin/hypermodeling-frontend": rc
  "@itwin/webgl-compatibility": rc
  # iTwinUI packages
  "@itwin/itwinui-react": "^3.18.3"
  "@stratakit/bricks": ^0.2.0
  "@stratakit/foundations": ^0.1.3
  # Icons
  "@bentley/icons-generic": ^1.0.34
  "@bentley/icons-generic-webfont": ^1.0.34
  # Other packages
  zustand: ^4.4.1

onlyBuiltDependencies:
  - "@bentley/imodeljs-native"
  - electron

patchedDependencies:
  "@changesets/assemble-release-plan": patches/@changesets__assemble-release-plan.patch
