packages:
  - ui/*
  - apps/*
  - e2e-tests
  - tools/codemod
  - docs/storybook

catalog:
  # iTwin.js core packages
  "@itwin/appui-abstract": ^5.1.0
  "@itwin/core-backend": ^5.1.0
  "@itwin/core-bentley": ^5.1.0
  "@itwin/core-common": ^5.1.0
  "@itwin/core-electron": ^5.1.0
  "@itwin/core-frontend": ^5.1.0
  "@itwin/core-geometry": ^5.1.0
  "@itwin/core-i18n": ^5.1.0
  "@itwin/core-orbitgt": ^5.1.0
  "@itwin/core-quantity": ^5.1.0
  "@itwin/ecschema-metadata": ^5.1.0
  "@itwin/ecschema-rpcinterface-common": ^5.1.0
  "@itwin/ecschema-rpcinterface-impl": ^5.1.0
  "@itwin/editor-backend": ^5.1.0
  "@itwin/editor-common": ^5.1.0
  "@itwin/editor-frontend": ^5.1.0
  "@itwin/express-server": ^5.1.0
  "@itwin/frontend-devtools": ^5.1.0
  "@itwin/hypermodeling-frontend": ^5.1.0
  "@itwin/webgl-compatibility": ^5.1.0
  # iTwinUI packages
  "@itwin/itwinui-react": ^3.19.6
  "@stratakit/bricks": ^0.5.0
  "@stratakit/foundations": ^0.4.0
  "@stratakit/icons": ^0.2.0
  "@stratakit/structures": ^0.5.0
  # Icons
  "@bentley/icons-generic": ^1.0.34
  "@bentley/icons-generic-webfont": ^1.0.34
  # Other packages
  zustand: ^4.4.1
  # Testing
  vitest: ^3.2.4
  # Tooling
  "@itwin/build-tools": ^5.3.2
  "@vitejs/plugin-react-swc": ^4.1.0
  rimraf: ^6.1.0
  vite: ^7.1.11
  vite-plugin-static-copy: ^3.1.4
  vite-tsconfig-paths: 5.1.4

onlyBuiltDependencies:
  - "@bentley/imodeljs-native"
  - electron

patchedDependencies:
  "@changesets/assemble-release-plan": patches/@changesets__assemble-release-plan.patch

minimumReleaseAge: 1440
