trigger:
  branches:
    include:
      - master

pr:
  drafts: false
  branches:
    include:
      - master

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Generate_Docs
    jobs:
      - job:
        displayName: Generate Docs
        workspace:
          clean: all
        pool:
          name: iModelTechCI
          demands: Agent.OS -equals Windows_NT

        steps:
          - checkout: self
            clean: true

          - task: NodeTool@0
            displayName: Use Node 18
            inputs:
              versionSpec: 18.x
              checkLatest: true

          - script: |
              git config --local user.email imodeljs-admin@users.noreply.github.com
              git config --local user.name imodeljs-admin
            displayName: Setup git config

          - script: node common/scripts/install-run-rush.js install
            displayName: rush install

          - script: node common/scripts/install-run-rush.js build
            displayName: rush build

          - script: node common/scripts/install-run-rush.js docs
            displayName: rush docs

          - task: CopyFiles@2
            displayName: "Copy generated docs to: $(Build.StagingDirectory)"
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/generated-docs
              TargetFolder: $(Build.StagingDirectory)/docs

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: AppUI Docs"
            inputs:
              PathtoPublish: "$(Build.StagingDirectory)/docs/"
              ArtifactName: "AppUI Docs"

          - powershell: |
              $commitMsg = @"
              $(Build.SourceVersionMessage)
              "@
              if ($commitMsg -match '^(\d+.\d+.\d+)$') {
                Write-Host `'$commitMsg`'` is a major/minor/patch version bump
                Write-Host '##vso[task.setvariable variable=ShouldPublish;]True'
              } else {
                Write-Host `'$commitMsg`'` is not a major/minor/patch version bump
                Write-Host '##vso[task.setvariable variable=ShouldPublish;]False'
              }
            displayName: Publish if major/minor/patch version bump
            condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'))

          - task: tagBuildOrRelease@0
            inputs:
              type: "Build"
              tags: "hasDocs"
            condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['ShouldPublish'], 'True'))

  - stage: Validate_Docs
    dependsOn: Generate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
    jobs:
      - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
        parameters:
          checkout: itwinjs-core
          useCurrentAppUIDocsArtifact: true
          ignoreAudit: true
