name: Report a bug 🐛
description: Let us know so we can fix it!
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve iTwin.js AppUI!
        Please describe what the expected behavior is vs. what actually happens.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validation:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Desktop (please complete the applicable information)
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
        - iTwin.js AppUI Version [e.g. 4.0.0]
        - iTwin.js Version [e.g. 3.6.2]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Check out [the contributor guide](https://github.com/iTwin/appui/blob/master/CONTRIBUTING.md) to get started:

        Just let us know you're working on it and we'd be happy to provide advice and feedback.
