name: Request a feature 💄
description: New ideas & improvements to AppUI are always welcome.
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make AppUI better!

        When suggesting an idea, give examples of the intended use case. Features that benefit the wider community are more likely to be prioritized.

        The best way to get your ideas into AppUI is to help us! We love contributions and are always happy to be provide feedback and advice. Check out [the contributor guide](https://github.com/iTwin/appui/blob/master/CONTRIBUTING.md) to get started.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: Ex. I'm always frustrated when [...]
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the Solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
