name: Ask a question❓
description: Please use [the community forum ](https://github.com/iTwin/appui/issues) for general questions about using iTwin.js AppUI.
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
      ❗Please use [the community forum](https://github.com/iTwin/itwinjs-core/discussions) for asking questions about how to use iTwin.js and best practices.
      The core iTwin.js team actively monitors the forum and we love seeing what people are working on! ❗
