/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/

import type { enable } from "../../../useStrataKit.js";
import type { StrataKitSymbol } from "../PreviewFeatures.js";

type UseStrataKit = ReturnType<typeof enable>;
type UseStrataKitModules = UseStrataKit[typeof StrataKitSymbol]["modules"];
type StrataKitIconModules = Omit<UseStrataKitModules, "@stratakit/mui">;
type StrataKitIconModule = keyof StrataKitIconModules;

/**
 * Maps web font icon names from @bentley/icons-generic-webfont to StrataKit icon modules.
 * @internal
 */
export const webFontToStrataKitIcon: {
  [key: string]: StrataKitIconModule;
} = {
  "icon-2d": "@stratakit/icons/2d.svg",
  // "icon-3d-photo": undefined,
  // "icon-3d-render": undefined,
  "icon-3d": "@stratakit/icons/3d.svg",
  // "icon-accusnaps": undefined,
  "icon-active": "@stratakit/icons/checkmark.svg",
  "icon-activity": "@stratakit/icons/activity.svg",
  "icon-add-circular": "@stratakit/icons/add-circle.svg",
  "icon-add": "@stratakit/icons/add.svg",
  "icon-airplane": "@stratakit/icons/airplane.svg",
  // "icon-airport": undefined,
  // "icon-alarm-alarm": undefined,
  // "icon-alarm-critical-alarm": undefined,
  // "icon-alarm-early-warning": undefined,
  // "icon-alarm-priority-1": undefined,
  // "icon-alarm-priority-2": undefined,
  // "icon-alarm-priority-3": undefined,
  // "icon-alarm-priority-4": undefined,
  // "icon-alarm-warning": undefined,
  // "icon-alarms-alarm": undefined,
  // "icon-alarms-critical-alarm": undefined,
  // "icon-alarms-early-warning": undefined,
  // "icon-alarms-priority-1": undefined,
  // "icon-alarms-priority-2": undefined,
  // "icon-alarms-priority-3": undefined,
  // "icon-alarms-priority-4": undefined,
  // "icon-alarms-warning": undefined,
  "icon-align-align-bottom": "@stratakit/icons/align-bottom.svg",
  "icon-align-align-center-horizontal":
    "@stratakit/icons/align-center-horizontal.svg",
  "icon-align-align-center-vertical":
    "@stratakit/icons/align-center-vertical.svg",
  "icon-align-align-left": "@stratakit/icons/align-left.svg",
  "icon-align-align-right": "@stratakit/icons/align-right.svg",
  "icon-align-align-top": "@stratakit/icons/align-top.svg",
  "icon-angle-measure": "@stratakit/icons/measure-angle.svg",
  // "icon-annotation-add": undefined,
  // "icon-annotation-info": undefined,
  // "icon-annotation-manager": undefined,
  // "icon-annotation-settings": undefined,
  // "icon-annotation-show": undefined,
  "icon-annotation": "@stratakit/icons/annotation.svg",
  // "icon-app-1": undefined,
  // "icon-app-2": undefined,
  // "icon-app-launcher": undefined,
  // "icon-applications": undefined,
  // "icon-apps-assetwise-2": undefined,
  // "icon-apps-assetwise": undefined,
  // "icon-apps-connect": undefined,
  // "icon-apps-issue-resolution": undefined,
  "icon-apps-itwin": "@stratakit/icons/itwin.svg",
  // "icon-apps-projectwise": undefined,
  // "icon-apps-sharepoint-2": undefined,
  // "icon-apps-sharepoint": undefined,
  "icon-archived": "@stratakit/icons/archive.svg",
  "icon-arrow-down": "@stratakit/icons/arrow-down.svg",
  "icon-arrow-left": "@stratakit/icons/arrow-left.svg",
  "icon-arrow-right": "@stratakit/icons/arrow-right.svg",
  "icon-arrow-up": "@stratakit/icons/arrow-up.svg",
  // "icon-asset-classification-hide": undefined,
  // "icon-asset-isolate": undefined,
  "icon-attach": "@stratakit/icons/attach.svg",
  "icon-automatic": "@stratakit/icons/automagic.svg",
  // "icon-automation": undefined,
  "icon-away": "@stratakit/icons/user-away.svg",
  "icon-basket": "@stratakit/icons/basket.svg",
  "icon-bentley-systems": "@stratakit/icons/brand-bentley-systems.svg",
  // "icon-blank": undefined,
  "icon-bolt-2": "@stratakit/icons/bolt.svg",
  "icon-bookmark": "@stratakit/icons/bookmark.svg",
  // "icon-boundary-offset": undefined,
  // "icon-browse-2": undefined,
  // "icon-browse": undefined,
  "icon-calendar": "@stratakit/icons/calendar.svg",
  // "icon-callout": undefined,
  "icon-camera-animation-disabled":
    "@stratakit/icons/camera-video-disabled.svg",
  "icon-camera-animation": "@stratakit/icons/camera-video.svg",
  // "icon-camera-eye": undefined,
  // "icon-camera-location": undefined,
  "icon-camera": "@stratakit/icons/camera.svg",
  // "icon-caret-down-2": undefined,
  "icon-caret-down": "@stratakit/icons/caret-down.svg",
  "icon-caret-left": "@stratakit/icons/caret-left.svg",
  "icon-caret-right": "@stratakit/icons/caret-right.svg",
  // "icon-caret-up-2": undefined,
  "icon-caret-up": "@stratakit/icons/caret-up.svg",
  // "icon-cell": undefined,
  "icon-charts": "@stratakit/icons/chart-bar.svg",
  // "icon-chat-new": undefined,
  "icon-chat": "@stratakit/icons/chat.svg",
  // "icon-check-in-document": undefined,
  // "icon-check-in": undefined,
  // "icon-check-out-document": undefined,
  // "icon-check-out": undefined,
  "icon-checkbox-deselect": "@stratakit/icons/checkbox-deselect.svg",
  "icon-checkbox-select": "@stratakit/icons/checkbox-select.svg",
  "icon-checkmark": "@stratakit/icons/checkmark.svg",
  "icon-chevron-down": "@stratakit/icons/chevron-down.svg",
  "icon-chevron-left": "@stratakit/icons/chevron-left.svg",
  "icon-chevron-right": "@stratakit/icons/chevron-right.svg",
  "icon-chevron-up": "@stratakit/icons/chevron-up.svg",
  "icon-circle": "@stratakit/icons/circle.svg",
  // "icon-clear-day": undefined,
  // "icon-clear-night": undefined,
  "icon-clipboard": "@stratakit/icons/clipboard.svg",
  // "icon-clipboard-copy-2": undefined,
  // "icon-clipboard-copy-3": undefined,
  // "icon-clipboard-copy": undefined,
  // "icon-clipboard-cut": undefined,
  // "icon-clipboard-paste-2": undefined,
  // "icon-clipboard-paste": undefined,
  "icon-clock": "@stratakit/icons/clock.svg",
  // "icon-close-2": undefined,
  "icon-close-circular": "@stratakit/icons/dismiss-circle.svg",
  "icon-close": "@stratakit/icons/dismiss.svg",
  "icon-cloud-download": "@stratakit/icons/cloud-download.svg",
  "icon-cloud-upload": "@stratakit/icons/cloud-upload.svg",
  "icon-cloud": "@stratakit/icons/cloud.svg",
  // "icon-clouds-broken": undefined,
  // "icon-clouds-scattered-day": undefined,
  // "icon-clouds-scattered-night": undefined,
  // "icon-coating-system-concrete": undefined,
  // "icon-coating-system-steelwork": undefined,
  "icon-collapse-all": "@stratakit/icons/collapse-rows-all.svg",
  "icon-collapse": "@stratakit/icons/collapse-rows.svg",
  // "icon-comments-add": undefined,
  // "icon-comments": undefined,
  "icon-compare": "@stratakit/icons/compare.svg",
  "icon-computer": "@stratakit/icons/computer.svg",
  // "icon-concrete-block": undefined,
  // "icon-consequence-failure": undefined,
  // "icon-construction-work-area": undefined,
  // "icon-convert": undefined,
  "icon-crop": "@stratakit/icons/crop.svg",
  // "icon-cross-section-alignment": undefined,
  // "icon-cross-section-dynamic": undefined,
  // "icon-cross-section": undefined,
  // "icon-cube-faces-bottom": undefined,
  // "icon-cube-faces-front": undefined,
  // "icon-cube-faces-iso-left": undefined,
  // "icon-cube-faces-iso-right": undefined,
  // "icon-cube-faces-left": undefined,
  // "icon-cube-faces-none": undefined,
  // "icon-cube-faces-rear": undefined,
  // "icon-cube-faces-right": undefined,
  // "icon-cube-faces-top": undefined,
  "icon-cursor-click": "@stratakit/icons/cursor-click.svg",
  "icon-cursor": "@stratakit/icons/cursor.svg",
  // "icon-dashboard-2": undefined,
  // "icon-data-visualization": undefined,
  "icon-database": "@stratakit/icons/database.svg",
  "icon-delete": "@stratakit/icons/delete.svg",
  // "icon-deliverable": undefined,
  // "icon-design-review": undefined,
  "icon-details": "@stratakit/icons/details.svg",
  "icon-developer": "@stratakit/icons/developer.svg",
  "icon-disconnect": "@stratakit/icons/disconnect.svg",
  // "icon-distance": undefined,
  // "icon-distribute-distribute-bottom": undefined,
  // "icon-distribute-distribute-center-horizontal": undefined,
  // "icon-distribute-distribute-center-vertical": undefined,
  // "icon-distribute-distribute-left": undefined,
  // "icon-distribute-distribute-right": undefined,
  // "icon-distribute-distribute-top": undefined,
  // "icon-document-compare": undefined,
  "icon-document-lock": "@stratakit/icons/document-locked.svg",
  "icon-document-reference": "@stratakit/icons/document-reference.svg",
  // "icon-document-set": undefined,
  "icon-document": "@stratakit/icons/document-blank.svg",
  "icon-documentation": "@stratakit/icons/documentation.svg",
  "icon-download": "@stratakit/icons/download.svg",
  // "icon-drag": undefined,
  "icon-draw": "@stratakit/icons/draw.svg",
  "icon-duplicate": "@stratakit/icons/duplicate.svg",
  // "icon-ec-class": undefined,
  // "icon-ec-schema": undefined,
  "icon-edit-all": "@stratakit/icons/edit-all.svg",
  // "icon-edit-object": undefined,
  "icon-edit": "@stratakit/icons/edit.svg",
  // "icon-element": undefined,
  "icon-ellipse": "@stratakit/icons/ellipse.svg",
  "icon-email-at": "@stratakit/icons/email-at.svg",
  "icon-email": "@stratakit/icons/email.svg",
  "icon-exit": "@stratakit/icons/exit.svg",
  "icon-expand-all": "@stratakit/icons/expand-rows-all.svg",
  "icon-expand": "@stratakit/icons/expand-rows.svg",
  "icon-export": "@stratakit/icons/export.svg",
  // "icon-external-apps": undefined,
  "icon-eyedropper-drop": "@stratakit/icons/eyedropper-drop.svg",
  "icon-eyedropper-filled": "@stratakit/icons/eyedropper-filled.svg",
  "icon-eyedropper": "@stratakit/icons/eyedropper.svg",
  "icon-feedback": "@stratakit/icons/feedback.svg",
  // "icon-file-types-amim": undefined,
  // "icon-file-types-archive": undefined,
  // "icon-file-types-audio": undefined,
  // "icon-file-types-autocad": undefined,
  // "icon-file-types-creative-cloud": undefined,
  // "icon-file-types-dgn-db-2": undefined,
  // "icon-file-types-dgn-db": undefined,
  // "icon-file-types-document": undefined,
  // "icon-file-types-dwg": undefined,
  // "icon-file-types-forms-shared-help": undefined,
  // "icon-file-types-forms-shared-success": undefined,
  // "icon-file-types-forms-shared": undefined,
  // "icon-file-types-forms-unshared-help": undefined,
  // "icon-file-types-forms-unshared-success": undefined,
  // "icon-file-types-image": undefined,
  // "icon-file-types-microstation": undefined,
  // "icon-file-types-mism": undefined,
  // "icon-file-types-msg": undefined,
  // "icon-file-types-pdf-markup": undefined,
  // "icon-file-types-pdf": undefined,
  // "icon-file-types-ppt": undefined,
  // "icon-file-types-raster": undefined,
  // "icon-file-types-revit": undefined,
  // "icon-file-types-rfa": undefined,
  // "icon-file-types-sketchup": undefined,
  // "icon-file-types-system": undefined,
  // "icon-file-types-txt-2": undefined,
  // "icon-file-types-txt": undefined,
  // "icon-file-types-unknown": undefined,
  // "icon-file-types-vector": undefined,
  // "icon-file-types-video": undefined,
  // "icon-file-types-visio": undefined,
  // "icon-file-types-word": undefined,
  // "icon-file-types-xls": undefined,
  // "icon-filter-outlined": undefined,
  "icon-filter": "@stratakit/icons/filter.svg",
  "icon-find": "@stratakit/icons/find.svg",
  "icon-fire-extinguisher": "@stratakit/icons/fire-extinguisher.svg",
  "icon-fit-to-view": "@stratakit/icons/fit-to-view.svg",
  // "icon-flag-2": undefined,
  "icon-flag": "@stratakit/icons/flag.svg",
  "icon-folder-add": "@stratakit/icons/folder-add.svg",
  "icon-folder-chevron-down": "@stratakit/icons/folder-chevron-down.svg",
  "icon-folder-chevron-up": "@stratakit/icons/folder-chevron-up.svg",
  "icon-folder-export": "@stratakit/icons/folder-export.svg",
  "icon-folder-import": "@stratakit/icons/folder-import.svg",
  // "icon-folder-large": undefined,
  "icon-folder-lock": "@stratakit/icons/folder-lock.svg",
  "icon-folder-opened": "@stratakit/icons/folder-open.svg",
  // "icon-folder-remove-2": undefined,
  "icon-folder-remove": "@stratakit/icons/folder-remove.svg",
  "icon-folder-shortcut": "@stratakit/icons/folder-shortcut.svg",
  "icon-folder": "@stratakit/icons/folder.svg",
  "icon-font-bold": "@stratakit/icons/font-bold.svg",
  "icon-font-color": "@stratakit/icons/font-color.svg",
  "icon-font-italic": "@stratakit/icons/font-italic.svg",
  "icon-font-size": "@stratakit/icons/font-size.svg",
  "icon-function": "@stratakit/icons/function.svg",
  "icon-gesture-one-finger-drag":
    "@stratakit/icons/gesture-one-finger-drag.svg",
  // "icon-gesture-one-finger-tap-double": undefined,
  "icon-gesture-one-finger-tap": "@stratakit/icons/gesture-one-finger-tap.svg",
  "icon-gesture-pinch": "@stratakit/icons/gesture-pinch.svg",
  "icon-gesture-touch": "@stratakit/icons/gesture-touch.svg",
  "icon-gesture-two-finger-drag":
    "@stratakit/icons/gesture-two-finger-drag.svg",
  "icon-gesture-two-finger-tap": "@stratakit/icons/gesture-two-finger-tap.svg",
  "icon-gesture-two-finger": "@stratakit/icons/gesture-two-finger.svg",
  "icon-globe": "@stratakit/icons/globe.svg",
  "icon-graph-bar": "@stratakit/icons/chart-bar.svg",
  "icon-graph-pie-chart": "@stratakit/icons/chart-pie.svg",
  "icon-graph-scatter-chart": "@stratakit/icons/graph-scatter-chart.svg",
  "icon-graph": "@stratakit/icons/chart-line.svg",
  "icon-group-ungroup": "@stratakit/icons/ungroup.svg",
  "icon-group": "@stratakit/icons/group.svg",
  // "icon-gyroscope": undefined,
  "icon-hand-2": "@stratakit/icons/hand.svg",
  // "icon-help-hollow": undefined,
  // "icon-help": undefined,
  "icon-hierarchy-tree": "@stratakit/icons/hierarchy-tree.svg",
  "icon-history": "@stratakit/icons/history.svg",
  "icon-home": "@stratakit/icons/home.svg",
  "icon-hourglass": "@stratakit/icons/hourglass.svg",
  // "icon-hub": undefined,
  "icon-i-beam": "@stratakit/icons/i-beam.svg",
  // "icon-image-2": undefined,
  "icon-image": "@stratakit/icons/image.svg",
  // "icon-imodel-2": undefined,
  // "icon-imodel-hollow-2": undefined,
  "icon-imodel-hollow": "@stratakit/icons/imodel.svg",
  // "icon-imodel-hub-sync": undefined,
  // "icon-imodel-hub": undefined,
  // "icon-imodel-schema": undefined,
  "icon-imodel": "@stratakit/icons/imodel.svg",
  // "icon-imodeljs": undefined,
  "icon-import": "@stratakit/icons/import.svg",
  "icon-important-very": "@stratakit/icons/important-very.svg",
  "icon-important": "@stratakit/icons/important.svg",
  // "icon-info-2": undefined,
  // "icon-info-hollow": undefined,
  "icon-info": "@stratakit/icons/info.svg",
  "icon-install": "@stratakit/icons/install.svg",
  "icon-isolate": "@stratakit/icons/isolate.svg",
  "icon-issue-report": "@stratakit/icons/issue.svg",
  // "icon-issue-resolution-add": undefined,
  // "icon-issue-resolution": undefined,
  // "icon-item": undefined,
  // "icon-itwin-mapping": undefined,
  "icon-label": "@stratakit/icons/label.svg",
  // "icon-layers-hide": undefined,
  // "icon-layers-isolate": undefined,
  "icon-layers": "@stratakit/icons/layers.svg",
  "icon-lightbulb-2": "@stratakit/icons/lightbulb.svg",
  "icon-lightbulb": "@stratakit/icons/lightbulb.svg",
  "icon-line": "@stratakit/icons/line.svg",
  "icon-link": "@stratakit/icons/link.svg",
  "icon-list": "@stratakit/icons/list.svg",
  "icon-location": "@stratakit/icons/location.svg",
  "icon-lock-unlocked": "@stratakit/icons/lock-unlocked.svg",
  "icon-lock": "@stratakit/icons/lock.svg",
  "icon-manager": "@stratakit/icons/manager.svg",
  "icon-map": "@stratakit/icons/map.svg",
  // "icon-measure-2d-hide": undefined,
  // "icon-measure-2d-show": undefined,
  // "icon-measure-2d": undefined,
  // "icon-measure-3d": undefined,
  "icon-measure-angle": "@stratakit/icons/measure-angle.svg",
  // "icon-measure-arc": undefined,
  "icon-measure-area": "@stratakit/icons/measure-area.svg",
  // "icon-measure-clear-3": undefined,
  // "icon-measure-clear": undefined,
  "icon-measure-distance": "@stratakit/icons/measure-distance.svg",
  "icon-measure-location": "@stratakit/icons/measure-location.svg",
  // "icon-measure-perpendicular": undefined,
  // "icon-measure-station": undefined,
  "icon-measure": "@stratakit/icons/measure.svg",
  // "icon-media-controls-circular-pause": undefined,
  // "icon-media-controls-circular-play": undefined,
  // "icon-media-controls-circular-stop": undefined,
  // "icon-media-controls-fast-backward": undefined,
  // "icon-media-controls-fast-forward": undefined,
  // "icon-media-controls-frame-backward": undefined,
  // "icon-media-controls-frame-forward": undefined,
  // "icon-media-controls-go-to-end": undefined,
  // "icon-media-controls-go-to-start": undefined,
  // "icon-media-controls-loop": undefined,
  // "icon-media-controls-pause": undefined,
  // "icon-media-controls-play-backward": undefined,
  // "icon-media-controls-play-section": undefined,
  // "icon-media-controls-play": undefined,
  // "icon-media-controls-record": undefined,
  // "icon-media-controls-stop": undefined,
  "icon-menu": "@stratakit/icons/menu.svg",
  "icon-merge": "@stratakit/icons/merge.svg",
  // "icon-mist": undefined,
  // "icon-model-hide": undefined,
  // "icon-model-isolate": undefined,
  "icon-model": "@stratakit/icons/model.svg",
  // "icon-more-2": undefined,
  // "icon-more-circular-vertical": undefined,
  "icon-more-circular": "@stratakit/icons/more-horizontal-circle.svg",
  // "icon-more-vertical-2": undefined,
  "icon-more-vertical-circular": "@stratakit/icons/more-vertical-circle.svg",
  "icon-more-vertical": "@stratakit/icons/more-vertical.svg",
  "icon-more": "@stratakit/icons/more-horizontal.svg",
  "icon-mouse-click-left": "@stratakit/icons/mouse-click-left.svg",
  "icon-mouse-click-right": "@stratakit/icons/mouse-click-right.svg",
  "icon-mouse-click-wheel": "@stratakit/icons/mouse-click-middle.svg",
  "icon-mouse-click": "@stratakit/icons/mouse-click.svg",
  // "icon-move-2": undefined,
  // "icon-move-below": undefined,
  "icon-move": "@stratakit/icons/move.svg",
  "icon-network": "@stratakit/icons/network.svg",
  "icon-new": "@stratakit/icons/new.svg",
  // "icon-node-query-connected": undefined,
  // "icon-node-query-disconnected": undefined,
  // "icon-node-query-downstream": undefined,
  // "icon-node-query-multi": undefined,
  // "icon-node-query-upstream": undefined,
  "icon-notification-settings": "@stratakit/icons/notifications-settings.svg",
  "icon-notification": "@stratakit/icons/notifications.svg",
  "icon-paintbrush": "@stratakit/icons/paint-brush.svg",
  "icon-palette": "@stratakit/icons/palette.svg",
  "icon-panorama-model": "@stratakit/icons/panorama-model.svg",
  "icon-panorama": "@stratakit/icons/panorama.svg",
  "icon-perspective": "@stratakit/icons/perspective.svg",
  "icon-pin": "@stratakit/icons/pin.svg",
  "icon-placeholder": "@stratakit/icons/placeholder.svg",
  // "icon-plan-drawing": undefined,
  // "icon-plan-floor": undefined,
  // "icon-plane": undefined,
  "icon-polygon": "@stratakit/icons/polygon.svg",
  "icon-print-preview": "@stratakit/icons/print-preview.svg",
  "icon-print-settings": "@stratakit/icons/print-settings.svg",
  "icon-print": "@stratakit/icons/print.svg",
  // "icon-probability-failure": undefined,
  // "icon-probability": undefined,
  "icon-process": "@stratakit/icons/process.svg",
  // "icon-profile": undefined,
  // "icon-progress-backward-2": undefined,
  // "icon-progress-backward-3": undefined,
  "icon-progress-backward": "@stratakit/icons/chevron-left.svg",
  // "icon-progress-forward-2": undefined,
  // "icon-progress-forward-3": undefined,
  "icon-progress-forward": "@stratakit/icons/chevron-right.svg",
  // "icon-project-large": undefined,
  "icon-properties-list": "@stratakit/icons/settings.svg",
  "icon-properties": "@stratakit/icons/properties.svg",
  "icon-puzzle": "@stratakit/icons/puzzle.svg",
  // "icon-pw-project": undefined,
  // "icon-pw-workarea": undefined,
  // "icon-quantities": undefined,
  // "icon-rain-day": undefined,
  // "icon-rain-night": undefined,
  // "icon-rain-shower": undefined,
  // "icon-range": undefined,
  "icon-re-center": "@stratakit/icons/re-center.svg",
  "icon-read-only": "@stratakit/icons/read-only.svg",
  "icon-records": "@stratakit/icons/records.svg",
  "icon-rectangle": "@stratakit/icons/rectangle.svg",
  "icon-redo": "@stratakit/icons/redo.svg",
  "icon-refresh": "@stratakit/icons/refresh.svg",
  // "icon-remove-2": undefined,
  "icon-remove": "@stratakit/icons/dismiss.svg",
  "icon-rename": "@stratakit/icons/rename.svg",
  "icon-reorder": "@stratakit/icons/reorder.svg",
  // "icon-repair": undefined,
  "icon-replace": "@stratakit/icons/replace.svg",
  // "icon-reporting-alignment-data": undefined,
  "icon-reports": "@stratakit/icons/report.svg",
  "icon-road": "@stratakit/icons/road.svg",
  "icon-rotate-left": "@stratakit/icons/rotate-left.svg",
  "icon-rotate-right": "@stratakit/icons/rotate-right.svg",
  // "icon-rotate": undefined,
  // "icon-rules": undefined,
  // "icon-safetibase": undefined,
  "icon-save-as": "@stratakit/icons/save-as.svg",
  "icon-save-settings": "@stratakit/icons/save-settings.svg",
  // "icon-save-update": undefined,
  "icon-save": "@stratakit/icons/save.svg",
  // "icon-saved-searches": undefined,
  // "icon-saved-view-annotate": undefined,
  // "icon-saved-view-chat": undefined,
  "icon-saved-view": "@stratakit/icons/saved-views.svg",
  // "icon-saved-views-move": undefined,
  // "icon-scale-2": undefined,
  "icon-scale": "@stratakit/icons/object-scale.svg",
  "icon-screenshare-stop": "@stratakit/icons/screenshare-stop.svg",
  "icon-screenshare": "@stratakit/icons/screenshare.svg",
  "icon-script-run": "@stratakit/icons/script-run.svg",
  "icon-script-status": "@stratakit/icons/script-status.svg",
  "icon-script": "@stratakit/icons/script.svg",
  "icon-search": "@stratakit/icons/search.svg",
  // "icon-section-clear": undefined,
  // "icon-section-element": undefined,
  // "icon-section-hide": undefined,
  // "icon-section-plane": undefined,
  // "icon-section-range": undefined,
  // "icon-section-shape": undefined,
  // "icon-section-show": undefined,
  // "icon-section-tool": undefined,
  // "icon-select-box": undefined,
  // "icon-select-line": undefined,
  // "icon-select-minus": undefined,
  // "icon-select-plus": undefined,
  // "icon-select-single": undefined,
  "icon-selection-clear": "@stratakit/icons/selection-clear.svg",
  "icon-selection": "@stratakit/icons/selection.svg",
  "icon-send": "@stratakit/icons/send.svg",
  "icon-settings": "@stratakit/icons/settings.svg",
  // "icon-shape": undefined,
  "icon-share": "@stratakit/icons/share.svg",
  // "icon-shortcut-add": undefined,
  // "icon-sitemap": undefined,
  "icon-smartphone": "@stratakit/icons/smartphone.svg",
  // "icon-smiley-happy-2": undefined,
  // "icon-smiley-happy-very-2": undefined,
  "icon-smiley-happy-very": "@stratakit/icons/smiley-very-happy.svg",
  "icon-smiley-happy": "@stratakit/icons/smiley-happy.svg",
  // "icon-smiley-neutral-2": undefined,
  "icon-smiley-neutral": "@stratakit/icons/smiley-neutral.svg",
  // "icon-smiley-sad-2": undefined,
  // "icon-smiley-sad-very-2": undefined,
  "icon-smiley-sad-very": "@stratakit/icons/smiley-very-sad.svg",
  "icon-smiley-sad": "@stratakit/icons/smiley-sad.svg",
  // "icon-snaps-bisector": undefined,
  // "icon-snaps-center": undefined,
  // "icon-snaps-intersection": undefined,
  // "icon-snaps-midpoint": undefined,
  // "icon-snaps-multione": undefined,
  // "icon-snaps-multithree": undefined,
  // "icon-snaps-multitwo": undefined,
  // "icon-snaps-nearest": undefined,
  // "icon-snaps-origin": undefined,
  // "icon-snaps": undefined,
  // "icon-snow": undefined,
  "icon-sort-down": "@stratakit/icons/sort-ascending.svg",
  "icon-sort-menu": "@stratakit/icons/sorting.svg",
  "icon-sort-up": "@stratakit/icons/sort-descending.svg",
  // "icon-spaces": undefined,
  // "icon-spatial-view-apply": undefined,
  "icon-spin": "@stratakit/icons/spin.svg",
  "icon-star-hollow": "@stratakit/icons/star.svg",
  // "icon-star": undefined,
  "icon-status-draft": "@stratakit/icons/status-draft.svg",
  "icon-status-error-hollow": "@stratakit/icons/status-error.svg",
  "icon-status-error": "@stratakit/icons/status-error.svg",
  // "icon-status-pass-hollow": undefined,
  // "icon-status-pass": undefined,
  "icon-status-pending-hollow": "@stratakit/icons/status-pending.svg",
  "icon-status-pending": "@stratakit/icons/status-pending.svg",
  "icon-status-rejected-hollow": "@stratakit/icons/status-rejected.svg",
  "icon-status-rejected": "@stratakit/icons/status-rejected.svg",
  "icon-status-running": "@stratakit/icons/status-running.svg",
  "icon-status-success-hollow": "@stratakit/icons/status-success.svg",
  "icon-status-success": "@stratakit/icons/status-success.svg",
  "icon-status-update": "@stratakit/icons/status-update.svg",
  "icon-status-warning": "@stratakit/icons/status-warning.svg",
  // "icon-sunrise": undefined,
  // "icon-sunset": undefined,
  // "icon-symbol": undefined,
  "icon-sync-disabled": "@stratakit/icons/cloud-offline.svg",
  "icon-sync": "@stratakit/icons/loop.svg",
  // "icon-table-2": undefined,
  "icon-table-of-contents": "@stratakit/icons/table-of-contents.svg",
  "icon-table": "@stratakit/icons/table.svg",
  // "icon-tag-2": undefined,
  "icon-technical-preview-badge-bw":
    "@stratakit/icons/technical-preview-badge.svg",
  // "icon-technical-preview-badge": undefined,
  "icon-technical-preview-bw": "@stratakit/icons/technical-preview.svg",
  "icon-technical-preview-mini-bw": "@stratakit/icons/technical-preview.svg",
  // "icon-technical-preview-mini": undefined,
  // "icon-technical-preview": undefined,
  // "icon-test": undefined,
  // "icon-text-align-text-align-center": undefined,
  // "icon-text-align-text-align-justify": undefined,
  // "icon-text-align-text-align-left": undefined,
  // "icon-text-align-text-align-right": undefined,
  // "icon-text-medium": undefined,
  // "icon-text-small": undefined,
  "icon-text": "@stratakit/icons/text.svg",
  // "icon-three-points-circular-arc": undefined,
  // "icon-thumbnails": undefined,
  // "icon-thunderstorm": undefined,
  // "icon-timeline": undefined,
  "icon-timer": "@stratakit/icons/timer.svg",
  // "icon-tools": undefined,
  // "icon-tree": undefined,
  "icon-underline": "@stratakit/icons/font-underline.svg",
  "icon-undo": "@stratakit/icons/undo.svg",
  "icon-unlink": "@stratakit/icons/unlink.svg",
  "icon-upgrade": "@stratakit/icons/update.svg",
  "icon-upload-to-cloud": "@stratakit/icons/cloud-upload.svg",
  "icon-upload": "@stratakit/icons/upload.svg",
  "icon-user-add": "@stratakit/icons/user-add.svg",
  "icon-user": "@stratakit/icons/user.svg",
  "icon-users": "@stratakit/icons/users.svg",
  "icon-validate": "@stratakit/icons/validate.svg",
  // "icon-versions": undefined,
  // "icon-vertex": undefined,
  // "icon-view-layouts": undefined,
  // "icon-view-navigation": undefined,
  "icon-visibility-half": "@stratakit/icons/visibility-partial.svg",
  // "icon-visibility-hide-2": undefined,
  "icon-visibility-hide": "@stratakit/icons/visibility-hide.svg",
  // "icon-visibility-invert": undefined,
  // "icon-visibility-semi-transparent": undefined,
  // "icon-visibility": undefined,
  "icon-walk": "@stratakit/icons/walk.svg",
  "icon-wifi-disabled": "@stratakit/icons/wifi-disabled.svg",
  "icon-wifi": "@stratakit/icons/wifi.svg",
  "icon-window-add": "@stratakit/icons/window-add.svg",
  "icon-window-area": "@stratakit/icons/window-area.svg",
  "icon-window-backward": "@stratakit/icons/window-back.svg",
  // "icon-window-collapse-2": undefined,
  "icon-window-collapse": "@stratakit/icons/window-collapse.svg",
  // "icon-window-expand": undefined,
  "icon-window-forward": "@stratakit/icons/window-forward.svg",
  "icon-window-full-screen": "@stratakit/icons/window-expand.svg",
  "icon-window-maximize": "@stratakit/icons/window-maximize.svg",
  "icon-window-minimize": "@stratakit/icons/window-minimize.svg",
  // "icon-window-new": undefined,
  "icon-window-settings": "@stratakit/icons/window-settings.svg",
  "icon-window-split-horizontal":
    "@stratakit/icons/window-split-horizontal.svg",
  "icon-window-split-vertical": "@stratakit/icons/window-split-vertical.svg",
  "icon-window": "@stratakit/icons/window.svg",
  "icon-windows": "@stratakit/icons/brand-windows.svg",
  // "icon-xray-view": undefined,
  // "icon-zoom-in-2": undefined,
  "icon-zoom-in": "@stratakit/icons/zoom-in-magnifier.svg",
  // "icon-zoom-out-2": undefined,
  "icon-zoom-out": "@stratakit/icons/zoom-out-magnifier.svg",
  // "icon-zoom": undefined,
};
