# This defines the core steps for building and validating iTwin.js Core

parameters:
  - name: workingDir
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: rushBuildCacheEnabled
    type: number
    default: 1

steps:
  - script: node common/scripts/set-rush-write-cache-variables.js
    displayName: "Set Rush Write Cache Variables"
  - script: node common/scripts/install-run-rush.js check
    displayName: rush check
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq(variables['variant'], ''))
  - script: node common/scripts/install-run-rush.js check --variant $(variant)
    displayName: rush check (variant)
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), ne(variables['variant'], ''))
  - task: PythonScript@0
    displayName: "rush change -v"
    inputs:
      workingDirectory: ${{ parameters.workingDir }}
      scriptSource: filepath
      scriptPath: common/scripts/run_rush_change.py
      arguments: $(Build.SourceBranch) $(Build.Reason) $(System.PullRequest.TargetBranch)
      failOnStderr: true
  - script: node common/scripts/install-run-rush.js install
    displayName: rush install
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq(variables['variant'], ''))
  - script: node common/scripts/install-run-rush.js install --variant $(variant)
    displayName: rush install (variant)
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), ne(variables['variant'], ''))
  - script: node common/scripts/install-run-rush.js audit
    displayName: rush audit
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), ne(variables['Agent.OS'], 'Darwin'))
  - script: node common/scripts/install-run-rush.js build -v -p max
    displayName: rush build
    workingDirectory: ${{ parameters.workingDir }}
    env:
      RUSH_BUILD_CACHE_CREDENTIAL: $(RushBuildCacheSAS)
      RUSH_BUILD_CACHE_ENABLED: ${{parameters.rushBuildCacheEnabled}}

  - script: node common/scripts/install-run-rush.js lint
    displayName: rush lint
    workingDirectory: ${{ parameters.workingDir }}

  - script: node common/scripts/install-run-rush.js prettier
    displayName: rush prettier
    workingDirectory: ${{ parameters.workingDir }}

  # By default linux agents do not have a real display so use the virtual framebuffer
  - script: xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' node common/scripts/install-run-rush.js cover --verbose
    displayName: rush cover
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
    env:
      CI: true
      BUILD_SOURCES_DIRECTORY: $(Build.SourcesDirectory)

  # MacOS and Windows agents work without any virtual display
  - script: node common/scripts/install-run-rush.js cover --verbose
    displayName: rush cover
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), ne(variables['Agent.OS'], 'Linux'))
    env:
      CI: true
      BUILD_SOURCES_DIRECTORY: $(Build.SourcesDirectory)

  # Run playwright tests
  - script: npm run test:e2e
    displayName: run playwright
    workingDirectory: "e2e-tests"
    env:
      CI: true
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

  # Run codemod tests
  - script: npm run test
    displayName: run Codemod Tests
    workingDirectory: "tools/codemod"
    condition: and(succeeded(), ne(variables['Agent.OS'], 'Linux'))

  - script: node common/scripts/install-run-rush.js docs
    displayName: rush docs
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq(variables['variant'], ''))
