# This defines the steps for publishing storybook to GitHub pages

parameters:
  - name: workingDir
    type: string
    default: $(System.DefaultWorkingDirectory)

steps:
  - script: node common/scripts/install-run-rush.js deploy:storybook --dest storybook
    displayName: Deploy main storybook
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - script: node common/scripts/install-run-rush.js deploy:storybook --dest $(System.PullRequest.PullRequestId)
    displayName: Deploy PR storybook
    workingDirectory: ${{ parameters.workingDir }}
    condition: and(succeeded(), in(variables['Build.Reason'], 'PullRequest'))
