name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Rush install
        run: node common/scripts/install-run-rush.js install

      - name: Rush build
        run: node common/scripts/install-run-rush.js build -v -p max

      - name: core-react tests
        run: npm run cover
        working-directory: ui/core-react

      - name: components-react tests
        run: npm run cover
        working-directory: ui/components-react

      - name: imodel-components-react tests
        run: npm run cover
        working-directory: ui/imodel-components-react

      - name: appui-react tests
        run: npm run cover
        working-directory: ui/appui-react

  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Rush cspell
        run: node common/scripts/install-run-rush.js cspell
