name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install

  audit:
    name: Audit node modules
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm audit

  check:
    name: Check code quality
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm cspell
      - run: pnpm prettier
      - run: pnpm lint:copyright
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm run docs

  test:
    name: Run unit tests
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build
      - run: pnpm cover

      - name: Run codemod tests
        run: npm run test
        working-directory: tools/codemod
        if: matrix.os == 'macos-latest'

  e2e:
    name: Run e2e tests
    needs: install
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - run: pnpm install
      - run: pnpm build

      - run: pnpm --filter=e2e-tests exec playwright test
        env:
          HOME: /root
