# Workflow to run cSpell on entire monorepo

name: cSpell

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - release/*

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Rush install
        run: node common/scripts/install-run-rush.js install

      - name: Rush cspell
        run: node common/scripts/install-run-rush.js cspell
