# Triggered on a new release git tag pushed, starts the final steps of a release.
#
# Steps currently include
#   1. Cherry-pick changelogs, change history, and other doc updates to master

name: Finalize Release

on:
  workflow_dispatch:
  push:
    tags:
      - "release/*"

jobs:
  finalize:
    name: Cherry-pick Changelogs to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Set Git Config
        run: |
          git config --local user.email 38288322+imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
      - name: Cherry-pick changelogs
        run: |
          git cherry-pick $commitid

          # Clean up files that we don't want to cherry-pick changes back
          for i in **/package.json; do git checkout --ours $i; done
          git checkout --ours **/version-policies.json docs/changehistory/NextVersion.md

          # Stage explicit files;
          #   - Files resolved due to taking master's version
          git add **/package.json **/version-policies.json docs/changehistory/NextVersion.md
          #   - All changelogs to remove duplicates from master
          #     - They would be duplicated if the same PR is backported to the release branch
          #       (On a separate command so it can fail because none exists without blocking masters version files)
          git add common/changes

          commitMessage=$(git log --format=%B -n 1 $commitid)
          git commit -m "$commitMessage Changelogs"

          exitCode=$?
          if [ $exitCode -ne 0 ]
          then
            echo Failed to cherry-pick changelogs for $commitMessage. Commit id is $commitid
            exit $exitCode
          fi

          rush change --bulk --message "" --bump-type none
          git add .
          git commit --amend --no-edit

          exit $?
        env:
          commitid: ${{ github.sha }}
        # turn off the default behavior to fail fast. The script has its own error handling
        shell: bash {0}
      - name: Push to master
        run: git push https://$(GITHUBTOKEN)@github.com/iTwin/appui HEAD:master
